### ISSUE TITLE
Build error: Could not find module ‘GHCJS.Marshal.Pure’

### ISSUE THREAD

**Issue by dimchansky** [ghcjs/ghcjs-dom#10]
Failed to build the latest version of [ghcjs-dom](https://github.com/ghcjs/ghcjs-dom/commit/cab5caab1689a2ea376eadbecc6dd3a4cb20ce68) (GHC: 7.8.4, [ghcjs](https://github.com/ghcjs/ghcjs/commit/30c107e863293641146c36b81ab9cfc3d6f1285d), [ghcjs-prim](https://github.com/ghcjs/ghcjs-prim/commit/bd83ce26f7e32fa9dc6c762d05ca595589d7b1a3)) with the following output:
```
src/GHCJS/DOM/ANGLEInstancedArrays.hs:15:8:
    Could not find module ‘GHCJS.Marshal.Pure’
    Perhaps you meant GHCJS.Marshal (from ghcjs-base-0.1.0.0)
    Use -v to see a list of the files searched for.
```

**Comment by bergey** [comment]
`GHCJS.Marshal.Pure` is in the `improved-base` branch of `ghcjs-base`.  Recent `ghcjs-dom` depends on this branch (and hence on GHC-7.10.2).
