### ISSUE TITLE
package qualified imports should use "ghcjs-dom-jsaddle" and not "jsaddle-dom"

### ISSUE THREAD

**Issue by maralorn** [ghcjs/ghcjs-dom#101]
Lines like this fail to compile with ghc 9.0:

https://github.com/ghcjs/ghcjs-dom/blob/90779f212a6fdc6a4884aff6a0e6b8d2e8850513/ghcjs-dom/src/GHCJS/DOM/Document.hs#L78

The build works after applying:
```
sed -i 's/import "jsaddle-dom" GHCJS.DOM.Document/import "ghcjs-dom-jsaddle" GHCJS.DOM.Document/' src/GHCJS/DOM/Document.hs
```

**Comment by hamishmack** [comment]
I think we fixed this
