### ISSUE TITLE
Where do I get ghcjs-base >=0.2.0.0

### ISSUE THREAD

**Issue by anton-dessiatov** [ghcjs/ghcjs-dom#11]
This package's cabal file says that it requires ```ghcjs-base >=0.2.0.0 && <0.3```. My ghcjs setup has only 0.1.0.0 and I cannot find anything with higher version number in [ghcjs-base repository](https://github.com/ghcjs/ghcjs-base).

Where could I get ```ghcjs-base >= 0.2.0.0``` to build ghcjs-dom?

**Comment by hamishmack** [comment]
You can either get the older version of ghcjs-dom from Hackage with:

    cabal install --ghcjs ghcjs-dom

Or install the improved-base branch of ghcjs and ghcjs-base that is a bit of a work in progress (requires GHC 7.10):

    git clone https://github.com/ghcjs/ghcjs.git
    cd ghcjs
    git checkout origin/improved-base
    cabal install
    ghcjs-boot --dev --ghcjs-boot-dev-branch improved-base --shims-dev-branch improved-base
