### ISSUE TITLE
Support for data attributes

### ISSUE THREAD

**Issue by andrewthad** [ghcjs/ghcjs-dom#12]
If I have an element like this:

    <div data-foo="bar"></div>

I don't think that ghcjs-dom gives me a way to get to the data attribute. I've look at the [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes) for this, and I can't find the word "dataset" mentioned anywhere in the ghcjs-dom source, so I assume that it's missing.

**Comment by mulderr** [comment]
There is [`Element.getDataset`](https://github.com/ghcjs/ghcjs-dom/blob/master/src/GHCJS/DOM/JSFFI/Generated/Element.hs#L694).

Never used it so just pointing out that something with "dataset" exists after all ;)

**Comment by hamishmack** [comment]
I think @mulderr is right so closing.  Let us know if `Element.getDataset` does not do what you need.
