### ISSUE TITLE
elementGetAttribute

### ISSUE THREAD

**Issue by andrewthad** [ghcjs/ghcjs-dom#13]
There is a function named `elementGetAttribute` in GHCJS.DOM.Element. I get an error in Chrome with a stack trace when I try to use it like this:

    str <- elementGetAttribute element "data-foo"

This is what it looks like:

    uncaught exception in Haskell main thread: TypeError: Cannot read property 'length' of null
    port-tagger.js?etag=Qal9tulb:8586 TypeError: Cannot read property 'length' of null
      at h$fromStr (port-tagger.js?etag=Qal9tulb:7696)
      at h$$yY (port-tagger.js?etag=Qal9tulb:43517)
      at h$mainLoop (port-tagger.js?etag=Qal9tulb:9518)
      at port-tagger.js?etag=Qal9tulb:3632
      at runIfPresent (port-tagger.js?etag=Qal9tulb:3650)
      at onGlobalMessage (port-tagger.js?etag=Qal9tulb:3691)

Also, this function is missing in the master branch.

**Comment by hamishmack** [comment]
Function is now just `getAttribute` in the `GHCJS.DOM.Element` module.  I think perhaps the old version did not return the right type (needed to be a `Maybe` and perhaps it was not).  Please reopen this if you can reproduce it with a more recent version of `GHCJS.DOM.Element.getAttribute`.
