### ISSUE TITLE
new ghcjs-base: GHCJS.Foreign does not implement FromJSString and ToJSString typeclass

### ISSUE THREAD

**Issue by kfigiela** [ghcjs/ghcjs-dom#14]
`ghc-7.10` and `improved-base` branches of `ghcjs` do not implement `FromJSString` and `ToJSString` typeclasses. 

For the time being I patched them to implement them in my setup, however `ghcjs-dom` should be updated with respect to this change.

**Comment by bergey** [comment]
Can this be closed?  `ghcjs-dom` now defines `FromJSString` and `ToJSString` in ways that are compatible with `improved-base`.
