### ISSUE TITLE
Module ‘GHCJS.Types’ does not export ‘castRef’

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/ghcjs-dom#18]
I've installed GHCJS according to https://github.com/ghcjs/ghcjs/tree/master#quick-start, which involves improved-base (version 0.2.0.0), and I'm getting

```
Building ghcjs-dom-0.2.1.0...
Preprocessing library ghcjs-dom-0.2.1.0...
[   1 of 1042] Compiling GHCJS.DOM.JSFFI.RTCPeerConnectionError ( src/GHCJS/DOM/JSFFI/RTCPeerConnectionError.hs, dist/build/GHCJS/DOM/JSFFI/RTCPeerConnectionError.js_o )
[   2 of 1042] Compiling GHCJS.DOM.Types  ( src/GHCJS/DOM/Types.hs, dist/build/GHCJS/DOM/Types.js_o )

src/GHCJS/DOM/Types.hs:860:32:
    Module ‘GHCJS.Types’ does not export ‘castRef’
```

And indeed DOM/Types.hs requires castRef and improved-base doesn't have it. Plenty of other packages installs fine, though I also have this problem:

```
Building jsaddle-0.2.1.0...
Preprocessing library jsaddle-0.2.1.0...
[ 1 of 12] Compiling Language.Javascript.JSaddle.Types ( src/Language/Javascript/JSaddle/Types.hs, dist/build/Language/Javascript/JSaddle/Types.js_o )

src/Language/Javascript/JSaddle/Types.hs:41:22:
    Not in scope: type constructor or class ‘JSArray’
```

**Comment by Mikolaj** [comment]
castRef is remove here: https://github.com/ghcjs/ghcjs-base/commit/aaa4d59117f37d1b9c60a154a9128b3bcc6301cd#diff-6419c16c87e54ad9a243f764b0d04059L8

**Comment by luite** [comment]
it must still be updated to improved-base i suspect

**Comment by Mikolaj** [comment]
I was led to believe the master branch (it's package version matches the one from Hackage) is already updated to improved-base (https://github.com/ghcjs/ghcjs-dom/issues/15#issuecomment-123535069). But perhaps it's updated vs an old version of improved base?

**Comment by luite** [comment]
Apologies, you're right. I did make some changes to the JSRef type recently in `improved-base` though, removing the phantom type argument (and thus making `castRef` redundant). that must be the actual reason.

**Comment by Mikolaj** [comment]
I'd make a PR, but I can't test it with most of the options and I don't know what to do with the ton of Generated modules.

**Comment by hamishmack** [comment]
I'll try to finish up the fix for ghcjs-dom this weekend.

**Comment by Mikolaj** [comment]
Thank you, Hamish!

**Comment by cartazio** [comment]
i built my ghcjs from improved base branch last weekend, and i hit this same problem when trying to build ghcjs-dom myself just now

**Comment by Mikolaj** [comment]
@cartazio: did you try the last commit, from last weekend (not on hackage, at least not then)? I didn't, but it looks promising. @hamishmack: do you want us to test it? Is it complete (enough)?

**Comment by cartazio** [comment]
I think I tried current master.  I'll check again when at my work station
environment again on Thursday.

**Comment by hamishmack** [comment]
Sorry forgot to mention here that this should be fixed now in master.  I'll do some tests this weekend and put it in hackage too.  It does need a bang up to data ghcjs though (well ghcjs-base to be exact).  If you get errors complaining that `GHCJS.Nullable` is missing then you need to update ghcjs.

**Comment by Mikolaj** [comment]
@hamishmack: oh, great, thank you. @luite: would it be too much to ask for some proper version numbers and .cabal deps in ghcjs-base (and ghcjs-dom) so that next we know if we have the right set? ;)

**Comment by Mikolaj** [comment]
I got the GHCJS.Nullable, reinstalled the whole ghcjs and now it compiles fine. Thank you! Closing.
