### ISSUE TITLE
Module ‘GHCJS.Types’ does not export ‘castRef'

### ISSUE THREAD

**Issue by jasonzoladz** [ghcjs/ghcjs-dom#21]
#18 was closed but I've hit the same issue this morning.  Using improved base.

Is it simply because the fix hasn't been pushed to Hackage?

Here's the log:

<img width="949" alt="screen shot 2015-10-03 at 8 15 36 am" src="https://cloud.githubusercontent.com/assets/8467728/10262854/434aa6d8-69a7-11e5-947b-eed465901e4c.png">

**Comment by hamishmack** [comment]
> Is it simply because the fix hasn't been pushed to Hackage?

Yes.  I have uploaded ghcjs-dom-0.2.2.0.

**Comment by jasonzoladz** [comment]
Awesome.  Thanks man.
