### ISSUE TITLE
(ghcjs) after JSRef renaming, build fail: ‘fromJSRef’ is not a (visible) method of class ‘FromJSVal’

### ISSUE THREAD

**Issue by alios** [ghcjs/ghcjs-dom#25]
Hi! 

After fresh install of ghcjs (+ ghcjs-boot) I now get a bunch of errors compiling ghcjs-dom with ghcjs. Something with the JSRef/JSVal renaming seems to make problems. Get hundreds of those

    src/GHCJS/DOM/Types.hs:26431:3:
       ‘toJSRef’ is not a (visible) method of class ‘ToJSVal’

    src/GHCJS/DOM/Types.hs:26432:14:
        ‘toJSRef’ is not a (visible) method of class ‘ToJSVal’

Comment by @mgsloan on IRC:   *"I would have assumed hamish and the PR creator to have tested that"*

**Comment by mgsloan** [comment]
PR referred to https://github.com/ghcjs/ghcjs-dom/pull/23  Travis didn't catch it either :P https://github.com/ghcjs/ghcjs-dom/issues/24

**Comment by kfigiela** [comment]
See PR #26, I manually patched this to the stage that it builds.
