### ISSUE TITLE
So I see a directory called "Generated", why aren't these files generated during the build?

### ISSUE THREAD

**Issue by ddssff** [ghcjs/ghcjs-dom#28]
It seems like a hazard to check generated files into version control.

**Comment by hamishmack** [comment]
It would introduce a dependency on the webkit IDL files and domconv-webkit (and its dependencies).  It would also complicate the build process (most likely requiring a custom Setup.hs).

**Comment by hamishmack** [comment]
We might generate them one day, but for now running https://github.com/ghcjs/domconv-webkit is not a big hassle and it keeps things simple for other tools like hackage and hoddock.  It is also nice because we can see in git the history of the Haskell files.
