### ISSUE TITLE
Why does initalization checks CLI args

### ISSUE THREAD

**Issue by Ericson2314** [ghcjs/ghcjs-dom#30]
https://github.com/ghcjs/ghcjs-dom/blob/master/src/GHCJS/DOM.hs#L134-L138 Huh? Seems very weird to impose this policy downstream.

@kmicklas

**Comment by hamishmack** [comment]
This is no longer the case.  For GHC you can use `run` to start a warp server on a local port of your choosing with default setup or you can use `jsaddleOr` to get more control over the warp server settings.  As far as I know we no longer use args.
