### ISSUE TITLE
setTimeout Type Signature

### ISSUE THREAD

**Issue by jeffersoncarpenter** [ghcjs/ghcjs-dom#31]
Trying to use `GHCJS.DOM.WindowTimers.setTimeout`; I think there's a problem with its type signature.

The type signature is:
`(MonadIO m) => WindowTimers -> JSVal -> Int -> m Int`
but I expected it to look something like
`(MonadIO m) => WindowTimers -> m () -> Int -> m Int`

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout) says that `setTimeout` "Calls a function or executes a code snippet after a specified delay".  But the type signature has a `JSVal`, not an IO type like I would expect for a code snippet.

Am I correct, that the type signature is wrong?  Or am I supposed to cast my code snippets to `JSVal`s?

**Comment by hamishmack** [comment]
You should be able to use `forkIO` and `threadDelay` instead.

**Comment by jeffersoncarpenter** [comment]
Perfect, that works.

Someone on IRC (maybe you) also commented that `setTImeout` has the right type signature; it's just a low-level function.
