### ISSUE TITLE
Document GTK/WebkitGTK setup on OS X

### ISSUE THREAD

**Issue by eallik** [ghcjs/ghcjs-dom#34]
It seems following these instructions for Leksah (ignoring the Leksah-specific bits) gets you a perfectly functional setup where ghcjs-dom can be used without GHCJS.

https://github.com/leksah/leksah#building-on-os-x

Would it make sense to include equivalent instructions in the GHCJS or `ghcjs-dom` setup guide for OS X?

Would it make sense for these instructions to be under `ghcjs-dom` or `ghcjs`? I'd personally favor them being under `ghcjs`, but then again if most people don't use `ghcjs-dom` and istead use `reflex-dom`, it might make sense to keep them here.

**Comment by dmjio** [comment]
+1 for this. Would like ghcjs-dom installation instructions for GHC w/ OSX. @eallik, If we could get it working with only `homebrew` that would also be nice. Two package managers is asking for trouble.

**Comment by eallik** [comment]
I created a working webkitgtk249 formula — it's in a PR (but the final version was broken due to the extreme requirements by the Homebrew maintainers, only to be rejected ultimately... oh well).

**Comment by eallik** [comment]
P.S I need to set up a tap — or would it make sense to create a tap under the WebKitGTK organisation repos? I'm open to suggestions and am willing to help set it up.

**Comment by dmjio** [comment]
Under the WebKitGTK org might be better. @eallik I couldn't even get webkitgtk3 installed via the leksah instructions.

After `stack install webkitgtk-3.0`

```bash
  [1 of 2] Compiling SetupWrapper     ( SetupWrapper.hs, /private/var/folders/m_/z586qg2d7gg1flh7y3nvw5600000gn/T/stack5226/webkitgtk3-0.14.1.1/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/setup/SetupWrapper.o )
    [2 of 2] Compiling Main             ( /private/var/folders/m_/z586qg2d7gg1flh7y3nvw5600000gn/T/stack5226/webkitgtk3-0.14.1.1/Setup.hs, /private/var/folders/m_/z586qg2d7gg1flh7y3nvw5600000gn/T/stack5226/webkitgtk3-0.14.1.1/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/setup/Main.o )
    Linking /private/var/folders/m_/z586qg2d7gg1flh7y3nvw5600000gn/T/stack5226/webkitgtk3-0.14.1.1/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/setup/setup ...
    [1 of 2] Compiling Gtk2HsSetup      ( Gtk2HsSetup.hs, dist/setup-wrapper/Gtk2HsSetup.o )
    [2 of 2] Compiling Main             ( SetupMain.hs, dist/setup-wrapper/Main.o )
    Linking dist/setup-wrapper/setup ...
    Configuring webkitgtk3-0.14.1.1...
    setup: The pkg-config package 'webkitgtk-3.0' version >=1.8 is required but it
    could not be found.
```

On 10.10.5. But it worked for you?

**Comment by dmjio** [comment]
I think `gtk-doc` couldn't verify the checksum.

```bash
Error: org.macports.checksum for port gtk-doc returned: gtk-doc-1.24.tar.xz does not exist in /opt/local/var/macports/distfiles/gtk-doc
Error: Failed to install gtk-doc
Please see the log file for port gtk-doc for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gtk-doc/gtk-doc/main.log
Error: The following dependencies were not installed: geoclue2 gtk-doc intltool gnome-common autoconf-archive p5.22-getopt-long p5.22-pathtools p5.22-scalar-list-utils p5.22-xml-parser p5.22-libwww-perl p5.22-encode-locale p5.22-file-listing p5.22-http-date p5.22-html-form p5.22-html-parser p5.22-html-tagset p5.22-http-message p5.22-io-html p5.22-lwp-mediatypes p5.22-uri p5.22-mime-base64 p5.22-http-cookies p5.22-http-daemon p5.22-http-negotiate p5.22-lwp-protocol-https p5.22-io-socket-ssl p5.22-net-libidn libidn p5.22-net-ssleay p5.22-test-exception p5.22-sub-uplevel p5.22-test-simple p5.22-test-nowarnings p5.22-test-warn p5.22-mozilla-ca p5.22-net-http p5.22-www-robotrules json-glib libsoup glib-networking curl-ca-bundle gnutls gmp libtasn1 nettle p11-kit desktop-file-utils popt gsettings-desktop-schemas libproxy vala gmake gstreamer1-gst-plugins-base gstreamer1 libogg libtheora libvorbis orc harfbuzz-icu libsecret libgcrypt libgpg-error py27-simplejson webp
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port webkit-gtk3 failed
```

**Comment by eallik** [comment]
Could someone possibly help with building the bottles for 10.11 and 10.10
and 10.9? I don't have the time nor resources but I can set up a properly
working formula/tap.
On Sun, 10 Jan 2016 at 01:31, David Johnson <notifications@github.com>
wrote:

> I think gtk-doc couldn't verify the checksum.
>
> Error: org.macports.checksum for port gtk-doc returned: gtk-doc-1.24.tar.xz does not exist in /opt/local/var/macports/distfiles/gtk-doc
> Error: Failed to install gtk-doc
> Please see the log file for port gtk-doc for details:
>     /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gtk-doc/gtk-doc/main.log
> Error: The following dependencies were not installed: geoclue2 gtk-doc intltool gnome-common autoconf-archive p5.22-getopt-long p5.22-pathtools p5.22-scalar-list-utils p5.22-xml-parser p5.22-libwww-perl p5.22-encode-locale p5.22-file-listing p5.22-http-date p5.22-html-form p5.22-html-parser p5.22-html-tagset p5.22-http-message p5.22-io-html p5.22-lwp-mediatypes p5.22-uri p5.22-mime-base64 p5.22-http-cookies p5.22-http-daemon p5.22-http-negotiate p5.22-lwp-protocol-https p5.22-io-socket-ssl p5.22-net-libidn libidn p5.22-net-ssleay p5.22-test-exception p5.22-sub-uplevel p5.22-test-simple p5.22-test-nowarnings p5.22-test-warn p5.22-mozilla-ca p5.22-net-http p5.22-www-robotrules json-glib libsoup glib-networking curl-ca-bundle gnutls gmp libtasn1 nettle p11-kit desktop-file-utils popt gsettings-desktop-schemas libproxy vala gmake gstreamer1-gst-plugins-base gstreamer1 libogg libtheora libvorbis orc harfbuzz-icu libsecret libgcrypt libgpg-error py27-simplejson webp
> To report a bug, follow the instructions in the guide:
>     http://guide.macports.org/#project.tickets
> Error: Processing of port webkit-gtk3 failed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ghcjs/ghcjs-dom/issues/34#issuecomment-170293389>.
>
-- 
Best Regards,
Erik Allik

**Comment by hamishmack** [comment]
I am closing this because ghcjs-dom does not depend on webkitgtk any more (it uses a warp websockets server to talk to any browser or javascript enabled web view).
