### ISSUE TITLE
Add requestAnimationFrame with a Haskell code as callback

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/ghcjs-dom#35]
[Edit: this is (partially) resolved. The new question is at the end.]

I wonder if it's possible to use this one

https://github.com/ghcjs/ghcjs-dom/blob/4c583f331ca89f5e8a5d1ef0ef0a8d78dca4d0e4/src/GHCJS/DOM/JSFFI/Generated/Window.hs#L388

so that the callback is really the Haskell code passed as an argument and not the whole Haskell RTS, with all the other threads currently running (and possibly not stopping any time soon, while requestAnimationFrame waits for the callback to finish before deciding it's time to repaint the browser window).

**Comment by Mikolaj** [comment]
Actually, after a closer look, let me first check if I can perhaps do that via newRequestAnimationFrameCallbackSync or similar.

**Comment by Mikolaj** [comment]
OK, it sort of works --- meaning it depends on how well the browser guesses the programmer intentions --- due to en extremely vague specification. In case of many Haskell threads running concurrently with the callback (I guess is always the case, regardless if the callback is newRequestAnimationFrameCallbackSync or newRequestAnimationFrameCallbackAsync), it usually guesses wrong, dropping some frames and drawing others twice. :( 

Anyway, the FFI seems correct, it's the JS itself that's the problem, so I'm closing the issue.

**Comment by Mikolaj** [comment]
Let me ask here: can I use the `requestAnimationFrame` when I compile for webkit? If not, can it be enabled? I will file a separate issue if that makes sense.

I have
```
import GHCJS.DOM.JSFFI.Generated.RequestAnimationFrameCallback
import GHCJS.DOM.JSFFI.Generated.Window (requestAnimationFrame)
```
and it works OK with --ghcjs, but with webkit I get
```
Game/LambdaHack/Client/UI/Frontend/Dom.hs:28:8: Could not find module ‘GHCJS.DOM.JSFFI.Generated.RequestAnimationFrameCallback’ …
    Use -v to see a list of the files searched for.
Game/LambdaHack/Client/UI/Frontend/Dom.hs:29:8: Could not find module ‘GHCJS.DOM.JSFFI.Generated.Window’ …
```

**Comment by cyrbon** [comment]
@Mikolaj 
If I'm not mistaken, you're importing internals. It's better to import modules like 

    import GHCJS.DOM.RequestAnimationFrameCallback
    import GHCJS.DOM.Window (requestAnimationFrame)


The `requestAnimationFrame` is indeed not in the GHCJS and the module RequestAnimationFrame is empty. Here is my own investigation.

GHCJS-DOM modules export conditionally either `webkitgtk3` haskell modules (when compiled natively) or generated JSFFI modules (when compliled with ghcjs). Inside the [GHCJS.DOM.RequestAnimationFrameCallback module](https://github.com/ghcjs/ghcjs-dom/blob/4c583f331ca89f5e8a5d1ef0ef0a8d78dca4d0e4/src/GHCJS/DOM/RequestAnimationFrameCallback.hs) the ghc version (else clause) does not export anything:


    module GHCJS.DOM.RequestAnimationFrameCallback (
    #if (defined(ghcjs_HOST_OS) && defined(USE_JAVASCRIPTFFI)) || !defined(USE_WEBKIT)
      module GHCJS.DOM.JSFFI.Generated.RequestAnimationFrameCallback
    #else
    #endif
      ) where
    #if (defined(ghcjs_HOST_OS) && defined(USE_JAVASCRIPTFFI)) || !defined(USE_WEBKIT)
    import GHCJS.DOM.JSFFI.Generated.RequestAnimationFrameCallback
    #else


In case of [`GHCJS.DOM.Window`](https://github.com/ghcjs/ghcjs-dom/blob/4c583f331ca89f5e8a5d1ef0ef0a8d78dca4d0e4/src/GHCJS/DOM/Window.hs):


    {-# LANGUAGE CPP #-}
    module GHCJS.DOM.Window (
    #if (defined(ghcjs_HOST_OS) && defined(USE_JAVASCRIPTFFI)) || !defined(USE_WEBKIT)
      module GHCJS.DOM.JSFFI.Window
    #else
      module Graphics.UI.Gtk.WebKit.DOM.Window
    #endif
      ) where
    #if (defined(ghcjs_HOST_OS) && defined(USE_JAVASCRIPTFFI)) || !defined(USE_WEBKIT)
    import GHCJS.DOM.JSFFI.Window
    #else
    import Graphics.UI.Gtk.WebKit.DOM.Window
    #endif

So, for GHC it re-exports modules (`Graphics.UI.Gtk.Webkit.DOM.Window`) from `webkitgtk3` (I believe this is how the package is called on hackage?) . That package is [here on github (same maintainer)](https://github.com/gtk2hs/webkit/blob/master/Graphics/UI/Gtk/WebKit/DOM/Window.chs) and it does not have any requestAnimation functions. 

`webkitgtk3` is a wrapper (c2hs) around webkit functions. It seems that webkit itself has `requestAnimationFrame` functions, but they were just not added to the `webkitgtk3`. For example, I found those webkit functions on github [here](https://github.com/WebKit/webkit/blob/master/Source/WebCore/page/DOMWindow.idl) and [here where it's more readable](http://www.gentoogeek.org/webkit-gtk-docs/html/d3/ddc/DOMWindow_8idl_source.html). If they are indeed in webkit, then it should be possible to add them to the `webkitgtk3` and they will become available in ghcjs-dom.

Perhaps, this is more of an issue for https://github.com/gtk2hs/webkit

**Comment by Mikolaj** [comment]
@cyrbon: thank you so much for your investigation. I will keep track of the issue I've just  issued on webkit and report here.

**Comment by Mikolaj** [comment]
P.S. to the original issue of dropping frames, now I no longer drop frames, after moving all Haskell computations to async threads and setting

    cpp-options:      -DGHCJS_BUSY_YIELD=100 -DGHCJS_SCHED_QUANTUM=1

at the cost of some drop in average FPS. See https://github.com/LambdaHack/LambdaHack/commit/c29418d04c781eb69cb0e48c846cc8349b9d6deb

**Comment by Mikolaj** [comment]
I suppose this is fixed, since I no longer get the compilation error. Thanks!
