### ISSUE TITLE
Why does querySelectorAll's last argument need to have an explicit type

### ISSUE THREAD

**Issue by 2426021684** [ghcjs/ghcjs-dom#44]
This works:
`Window.getComputedStyle window (Just element) (Nothing :: Maybe String)`

This does not:
`Window.getComputedStyle window (Just element) Nothing`

I think the second one should work too.

**Comment by mgsloan** [comment]
I haven't looked, but it's probably due to an `IsJSString` or `IsString` constraint.  `Nothing :: Maybe a`, so it doesn't know which string type you're using.

**Comment by hamishmack** [comment]
I think we should `noString = Nothing :: Maybe String`, `noText = ...` and `noDOMString = ...` along with `no*` for all the DOM types (e.g. `noHTMLElement = ...`).

**Comment by hamishmack** [comment]
I have added **lots** of

```
noX :: Maybe X
noX = Nothing
```

functions to `GHCJS.DOM.Types`.

I did not add `noText` and `noString` since I think using `noJSString` is a better choice (and if the compiler complains that the it needs to be `Maybe Text` or `Maybe String` instead then `Nothing` should work).
