### ISSUE TITLE
Build not working on OS X with webkit gtk

### ISSUE THREAD

**Issue by 2426021684** [ghcjs/ghcjs-dom#45]
```
Linking dist/setup-wrapper/setup ...
    Configuring webkitgtk3-0.14.1.1...
    setup: The pkg-config package 'webkitgtk-3.0' version >=1.8 is required but it could not be found.
```
How can I fix this? I installed webkit-gtk from homebrew and it still errors.

**Comment by hamishmack** [comment]
ghcjs-dom needs WebKitGtk 2.4.x and last time I checked homebrew only had a newer version that has dropped the old WebKit 1 interface.  WebKit 2 uses separate processes for rendering which means all DOM manipulate has to be done by sending JS to the rendering process or by making a WebKit2 extension and setting using some form of RPC to communicate with it.

MacPorts has both the 2.4.x WebKitGtk and the newer one, but you may find you need to compile GHC with macrports to get it to use the MacPorts libiconv.

**Comment by 2426021684** [comment]
I managed to get it working by using nix.
I added the following lines to `stack.yaml`:
```
system-ghc: false
nix:
  enable: true
  packages: [gnome3.webkitgtk24x, pkgconfig, cairo]
```

**Comment by hamishmack** [comment]
Oh cool!  Was that on OS X ?  I did not know it had webkitgtk24x.
