### ISSUE TITLE
Why isn't there setStyle as we have getStyle in GHCJS.DOM.JSFFI.Generated.Element?

### ISSUE THREAD

**Issue by qrilka** [ghcjs/ghcjs-dom#51]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style referenced from `getStyle` declararion shows examples of modifying styles but it doesn't seem to be possible with `ghcjs-dom` or maybe I miss something here?

**Comment by mulderr** [comment]
`getStyle` returns a newtype wrapper around JSVal which is mutable. This seems to work:

```haskell
import GHCJS.DOM
import GHCJS.DOM.Document
import GHCJS.DOM.Element
import GHCJS.DOM.CSSStyleDeclaration
import GHCJS.DOM.Node

main :: IO ()
main = runWebGUI $ \wv -> do
  Just doc <- webViewGetDomDocument wv
  Just body <- getBody doc
  Just d <- createElement doc (Just "div")
  Just styleDecl <- getStyle d
  setCssText styleDecl (Just "height: 100px; background-color: #aaa;")
  appendChild body (Just d)
  return ()
```

See [here](https://github.com/ghcjs/ghcjs-dom/blob/master/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/CSSStyleDeclaration.hs) for other ways to modify it.

**Comment by qrilka** [comment]
Thanks, I suppose that should do the trick
