### ISSUE TITLE
Add "unsafe" and "_" versions of functions that return Maybe

### ISSUE THREAD

**Issue by hamishmack** [ghcjs/ghcjs-dom#53]
Returning Maybe will always require synchronisation with JavaScript.  We should generate unsafe versions of these functions so they can run asynchronously.  Instead of:

     Just x <- getElementById doc "x"

You could write:

     x <- unsafeGetElementById doc "x"

The check for null or undefined will be skipped.

**Comment by hamishmack** [comment]
We should also generate "_" versions that throw away the result and `return ()` so that:

    removeProperty s "background"

Can be replaced with

    removeProperty_ s "background"

**Comment by mgsloan** [comment]
Makes sense to me!  How about having `getElementByIdEx`, which is essentially:

```
getElementByIdEx doc txt = do
    mresult <- getElementById
    case mresult of
        Nothing -> fail "getElementById failed to yield a result"
        Just result -> return result
```

It might be good to have the error include the `txt` value.  One possibility would also be to put in the `doc` object, and use `console.log`.  In chrome, this results in the object being interrogateable in the console.  So it should be possible to log all inputs when outputting the error to the console.  Then, throw a simpler error via `fail`.

**Comment by hamishmack** [comment]
I have added `_` and `Unchecked` versions.  I wonder if we could use `HasCallStack` to get nice error messages out of `getElementByIdUnchecked` (instead of adding `Ex` variant).  For now I just used `fromJust` in the `ghcjs-dom-jsffi` code.

**Comment by hamishmack** [comment]
@mgsloan just testing it out now and it seems like it will work nicely:
```
ghcjs-dom-hello: Nothing to return
CallStack (from HasCallStack):
  error, called at src/JSDOM/Generated/Document.hs:676:21 in jsaddle-dom-0.5.0.0-inplace:JSDOM.Generated.Document
  getElementByIdUnsafe, called at src/Main.hs:24:9 in main:Main
```
