### ISSUE TITLE
Since the run function is gone, how does it work now?

### ISSUE THREAD

**Issue by 2426021684** [ghcjs/ghcjs-dom#59]
What do I use instead of `run`?

**Comment by hamishmack** [comment]
There are now multiple run functions in different packages (although `id` will work if you only need GHCJS to work).

The `run` functions are all the same on GHCJS, but have different behaviour on GHC (and different `build-depends`).

`jsaddle-webkitgtk` `Language.Javascript.JSaddle.WebKitGTK.run` this is the most like the old run function.  It uses the WebKit1 version of GTK.

`jsaddle-webkit2gtk` `Language.Javascript.JSaddle.WebKitGTK.run` uses WebKit2 (so works with newer versions of WebKitGTK).

`jsaddle-wkwebview` `Language.Javascript.JSaddle.WKWebView.run` for use on Mac OS and iOS (still working on getting this one right).

`jsaddle-warp` `Language.Javascript.JSaddle.Warp.run` runs a local HTTP and WebSockets server on the specified port.  The code will run when you connect a browser to `http://localhost:{port}/`.
