### ISSUE TITLE
How about some documentation for EventM?

### ISSUE THREAD

**Issue by Profpatsch** [ghcjs/ghcjs-dom#60]
It’s very disheartening that event handling seems to work somehow, but the user has to painstakingly reverse-engineer how the api is supposed to work.

For functions like `on` it’s basically impossible to know what stuff like `-> IO (IO ())` means without studying the source.

**Comment by hamishmack** [comment]
The IO (IO ()) type for `on` is an IO action that adds the event handler and returns another IO action that removes and frees the event handler.

**Comment by Profpatsch** [comment]
Was fixed by #61.
