### ISSUE TITLE
Bind to a version of webkit that supports KeyboardEvent.key

### ISSUE THREAD

**Issue by Mikolaj** [ghcjs/ghcjs-dom#62]
KeyboardEvent.key, the new standard that all browsers, except Safari already support, has been added to webkit: https://bugs.webkit.org/show_bug.cgi?id=36267

A version of WebKitGTK+ with support for key and code properties on keyboard events has just been released: https://webkitgtk.org/2017/01/20/webkitgtk2.15.3-released.html

**Comment by Mikolaj** [comment]
@hamishmack: would that be a good moment to update to some newer upstream webkit? could I help? thank you!

**Comment by Mikolaj** [comment]
@hamishmack: ping! :)

**Comment by Mikolaj** [comment]
BTW, WebKitGTK+ 2.16.1, the new stable version, is just out.

**Comment by Mikolaj** [comment]
And, pretty please, set the `ENABLE_KEYBOARD_KEY_ATTRIBUTE` flag when generating the bindings (https://trac.webkit.org/changeset/206750/webkit/trunk/Source/WTF/wtf/FeatureDefines.h). It's set by default only when compiling webkit on Apple platforms, but I critically depend on it, because all modern browsers implement it and the new browsers already started dropping the old, faulty key handling hacks.

**Comment by hamishmack** [comment]
I think we have these now:

https://github.com/ghcjs/ghcjs-dom/blob/master/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/KeyboardEvent.hs#L112

https://github.com/ghcjs/ghcjs-dom/blob/master/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/KeyboardEvent.hs#L120

**Comment by Mikolaj** [comment]
You rock.

Will reopen if this doesn't work for me, but it looks perfect right now.
