### ISSUE TITLE
Missing functions/types

### ISSUE THREAD

**Issue by eskimor** [ghcjs/ghcjs-dom#63]
I just noticed that some functions/types are missing from this astonishingly complete package.

For example:

```
navigator.mediaDevices.enumerateDevices
```

or the new promise based getUserMedia:

```
navigator.mediaDevices.getUserMedia
```

I don't know wether those are already in a more recent version of webkitgtk, but if so would an update be possible?

Thank you!

**Comment by hamishmack** [comment]
[mediaDevices](https://github.com/ghcjs/ghcjs-dom/blob/49c3e1cd02a350e609b7fb163a0cac38e3099160/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/Navigator.hs#L216), [enumerateDevices](https://github.com/ghcjs/ghcjs-dom/blob/3c495cd71b2bdcc2013d305d2fab944fd9b5650a/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/MediaDevices.hs#L36) and [getUserMedia](https://github.com/ghcjs/ghcjs-dom/blob/3c495cd71b2bdcc2013d305d2fab944fd9b5650a/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/MediaDevices.hs#L65) are all now present.  They should work with ghcjs and ghc/jsaddle if the web and JS engines used support them (more likely to be supported with jsaddle-webkit2gtk than jsaddle-webkitgtk).
