### ISSUE TITLE
RTCIceCandidate methods should return Maybe.

### ISSUE THREAD

**Issue by eskimor** [ghcjs/ghcjs-dom#66]
Functions:
- getSdpMid
- getSdpMLineIndex

in [RTCIceCandidate.hs](https://github.com/ghcjs/ghcjs-dom/blob/master/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/RTCIceCandidate.hs) should return Maybe values, because according to the [Spec](https://www.w3.org/TR/webrtc/#rtcicecandidate-interface) they might be null.

**Comment by hamishmack** [comment]
This seems to have been fixed in the IDL files and in the [latest version](https://github.com/ghcjs/ghcjs-dom/blob/49c3e1cd02a350e609b7fb163a0cac38e3099160/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/RTCIceCandidate.hs#L55) they are now returning Maybe.

**Comment by eskimor** [comment]
Awesome! Thank you! :-)
