### ISSUE TITLE
getAttachedShaders in GHCJS.DOM.JSFFI.Generated.WebGLRenderingContextBase has the wrong return type

### ISSUE THREAD

**Issue by schell** [ghcjs/ghcjs-dom#68]
It seems that `getAttachedShaders` in `GHCJS.DOM.JSFFI.Generated.WebGLRenderingContextBase` has the wrong return type. The webgl call returns a list of `WebGLShader`s, but the given return type in ghcjs* is `m ()`. I'm pretty sure these are auto-generated, so maybe something just needs to be updated?
 
Here's a shot of the haddocks I generated locally:
<img width="846" alt="screenshot 2017-05-01 10 37 13" src="https://cloud.githubusercontent.com/assets/24942/25587790/5608dfaa-2e5a-11e7-9a80-46ec64896d4f.png">

And here's a link to the related webgl call (https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getAttachedShaders)

**Comment by hamishmack** [comment]
What version is that?  It looks ok in the [latest version](https://github.com/ghcjs/ghcjs-dom/blob/49c3e1cd02a350e609b7fb163a0cac38e3099160/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/WebGLRenderingContextBase.hs#L1126).

**Comment by schell** [comment]
Well, it's `0.7.0.4` so I guess that solves it! I'll update my stack.yaml to make sure it's pulling the latest, or wait a spell for the changes to percolate. Thanks @hamishmack :)
