### ISSUE TITLE
ghcjs-dom-jsffi rejected promise can't be handled + proposed fix.

### ISSUE THREAD

**Issue by eskimor** [ghcjs/ghcjs-dom#75]
JS imports usually are in the form of:

```
foreign import javascript interruptible
        "$1[\"createAnswer\"]($2).then($c);" js_createAnswer ::
        RTCPeerConnection ->
          Optional RTCAnswerOptions -> IO RTCSessionDescriptionInit
```

They have a `then` case, which with some ghcjs magic continues in the IO monad. But what happens with the `catch` case? Can this be handled with JS.catch from jsaddle?

**Comment by eskimor** [comment]
It seems it is in fact not possible for ghcjs-dom to handle the error case. For jsaddle-dom this is properly handled by means of readPromise as it seems. We will simply try to use jsaddle-dom in our ghcjs build for now. I would file a PR, but the code generation stuff is too much magic to handle right now.

**Comment by eskimor** [comment]
Rejected promises can be handled with a minor modification.

The following 
```haskell
foreign import javascript interruptible
        "$1[\"createOffer\"]($2).then($c);" js_createOffer ::
        RTCPeerConnection ->
          Optional RTCOfferOptions -> IO RTCSessionDescriptionInit

createOffer ::
            (MonadIO m) =>
              RTCPeerConnection ->
                Maybe RTCOfferOptions -> m RTCSessionDescriptionInit
createOffer self offerOptions
  = liftIO (js_createOffer self (maybeToOptional offerOptions))
```

should be something like this:

```haskell
foreign import javascript interruptible
        "$1[\"createOffer\"]($2).then(function(s) { $c(null, s);}, function(e) { $c(e, null);});" js_createOffer ::
        JS.RTCPeerConnection ->
          JS.Optional JS.RTCOfferOptions -> IO (JS.JSVal, JS.RTCSessionDescriptionInit)

createOffer ::
            (MonadIO m) =>
              JS.RTCPeerConnection ->
                Maybe JS.RTCOfferOptions -> m JS.RTCSessionDescriptionInit
createOffer self offerOptions
  = liftIO $ do
  (e, s) <- (js_createOffer self (JS.maybeToOptional offerOptions))
  unless (JS.isNull e) $ throwIO (JS.PromiseRejected e)
  pure s
```

We tested this scheme successfully with a dummy function (working code):
```haskell
foreign import javascript interruptible
        "testFFI($1).then(function(s) { $c(null, s);}, function(e) { $c(e, null);});" js_testFFI ::
        Bool -> IO (JS.JSVal, JS.JSVal)

testFFI :: (MonadIO m) => Bool -> m JS.JSVal
testFFI b = liftIO $ do
  (e, s) <- js_testFFI b
  unless (JS.isNull e) $ throwIO (JS.PromiseRejected e)
  pure s

main = do
  putStrLn "Before promise - *drums*!"
  (testFFI False >> pure ()) `catch` (\(e :: JS.PromiseRejected) -> putStrLn "Caught Exception")
  putStrLn "After promise - yeah!"
```

with the following testFFI JS function:

```javascript
       function testFFI(b) {
           return (new Promise(function(accept,reject) {
               if(b)
                   accept(null);
               else
                   reject("baaaaam euda");
           }));
       }
```

Many thanks!

**Comment by eskimor** [comment]
We could also try to fix the generator ourselves, if you could point us to the sources. (generator + idl files)

**Comment by hamishmack** [comment]
Please let me know if this works ok.  The change to the generator is [here](https://github.com/ghcjs/domconv-webkit/commit/205e5d4c5ef772b18a1d95d872fe2c578b9c7b32).  The IDL files are in [webkitgtk 2.17.2](https://webkitgtk.org/releases/webkitgtk-2.17.2.tar.xz) (the more recent versions use incompatible new features).

**Comment by eskimor** [comment]
Many thanks, I will check this out immediately! :-)

**Comment by eskimor** [comment]
Ok, what I can say already:

- The generated code looks really good to me
- Everything compiles fine
- My application works with the new libraries

-> Not yet tested: Whether the rejected case handling really works - I have to shim functionality for this, in order to test this efficiently. That being said, I am pretty confident it will will work as expected.

**Comment by eskimor** [comment]
I can confirm - it works as expected! Many thanks!
